module.exports = {
    1: {title: 'firs post', content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi molestias ea atque eveniet eos aspernatur beatae harum ex nemo nesciunt, labore nisi eligendi voluptas mollitia dolor a ad quia consequuntur.'},
    2: {title: 'second .post', content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi molestias ea atque eveniet eos aspernatur beatae harum ex nemo nesciunt, labore nisi eligendi voluptas mollitia dolor a ad quia consequuntur.'},
    3: {title: 'any post', content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi molestias ea atque eveniet eos aspernatur beatae harum ex nemo nesciunt, labore nisi eligendi voluptas mollitia dolor a ad quia consequuntur.'},
    4: {title: 'My #post', content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi molestias ea atque eveniet eos aspernatur beatae harum ex nemo nesciunt, labore nisi eligendi voluptas mollitia dolor a ad quia consequuntur.'},
    5: {title: 'OurPost', content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi molestias ea atque eveniet eos aspernatur beatae harum ex nemo nesciunt, labore nisi eligendi voluptas mollitia dolor a ad quia consequuntur.'},
    6: {title: 'Lorem% post', content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi molestias ea atque eveniet eos aspernatur beatae harum ex nemo nesciunt, labore nisi eligendi voluptas mollitia dolor a ad quia consequuntur.'},
    7: {title: 'Best_post!', content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi molestias ea atque eveniet eos aspernatur beatae harum ex nemo nesciunt, labore nisi eligendi voluptas mollitia dolor a ad quia consequuntur.'},
    8: {title: 'Bad post', content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi molestias ea atque eveniet eos aspernatur beatae harum ex nemo nesciunt, labore nisi eligendi voluptas mollitia dolor a ad quia consequuntur.'},
    9: {title: 'SuperPost15', content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi molestias ea atque eveniet eos aspernatur beatae harum ex nemo nesciunt, labore nisi eligendi voluptas mollitia dolor a ad quia consequuntur.'},
    10: {title: '78post', content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi molestias ea atque eveniet eos aspernatur beatae harum ex nemo nesciunt, labore nisi eligendi voluptas mollitia dolor a ad quia consequuntur.'},
    11: {title: '13 post', content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi molestias ea atque eveniet eos aspernatur beatae harum ex nemo nesciunt, labore nisi eligendi voluptas mollitia dolor a ad quia consequuntur.'},
};